woking_directory = "~"                                  # working directory of the running process
environment = "venv"                                    # activate virtual environment relative to working directory
output = "fib_run"                                       # redirect stdout and stderr of all processes into files, relative to working directory
assign = "assignments.csv"                              # file containing the assignments for the runs with their numbers
executable = "python fib.py"                            # executable file relative to working directory
fix_arguments = ""                                      # Arguments which are always the same for every run
var_arguments = [                                       # list of arguments which are varied for every run
        {"arg"="-n", "start"=0, "end"=40, "step"=1},    # arg -> command line argument, start and end -> range of values (inclusive upper bound) , step -> step size
        #{"arg"="-p", "start"=0, "end"=10, "step"=1},    # just as an example
]
